# $ mint run xcodegen

name: CatScreeningML
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    macOS: "15.2"
targets:
  CatScreeningML:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
      - target: MultiLabelClassification
      - target: OvRClassification
      - target: OvOClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatScreeningML
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CSInterface:
    type: framework
    platform: macOS
    sources:
      - path: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CSInterface
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  BinaryClassification:
    type: framework
    platform: macOS
    sources:
      - path: BinaryClassification/BinarySources
    resources:
      - path: BinaryClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  BinaryTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: BinaryClassification/BinaryTests
    resources:
      - path: BinaryClassification/BinaryTests/TestResources
        onDemand: false
    dependencies:
      - target: BinaryClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiClassClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiClassClassification/MultiClassSources
    resources:
      - path: MultiClassClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiClassTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MultiClassClassification/MultiClassTests
    resources:
      - path: MultiClassClassification/MultiClassTests/TestResources
        onDemand: false
    dependencies:
      - target: MultiClassClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiLabelClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiLabelClassification/MultiLabelSources
    resources:
      - path: MultiLabelClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiLabelClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiLabelTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MultiLabelClassification/MultiLabelTests
    resources:
      - path: MultiLabelClassification/MultiLabelTests/TestResources
        onDemand: false
    dependencies:
      - target: MultiLabelClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiLabelTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvRClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvRClassification/OvRSources
    resources:
      - path: OvRClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvRClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvRTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: OvRClassification/OvRTests
    resources:
      - path: OvRClassification/OvRTests/TestResources
        onDemand: false
    dependencies:
      - target: OvRClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvRTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvOClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvOClassification/OvOSources
    resources:
      - path: OvOClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvOClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvOTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: OvOClassification/OvOTests
    resources:
      - path: OvOClassification/OvOTests/TestResources
        onDemand: false
    dependencies:
      - target: OvOClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvOTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
