# $ mint run xcodegen

name: TrainCatScreeningML
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    macOS: "15.2"
targets:
  TrainCatScreeningML:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
      - target: MultiLabelClassification
      - target: OvRClassification
      - target: OvOClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TrainCatScreeningML
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  TrainCatScreeningMLTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: TrainCatScreeningMLTests
    resources:
      - path: TrainCatScreeningMLTests/BinaryTests/TestResources
        onDemand: false
      - path: TrainCatScreeningMLTests/MultiClassTests/TestResources
        onDemand: false
      - path: TrainCatScreeningMLTests/MultiLabelTests/TestResources
        onDemand: false
      - path: TrainCatScreeningMLTests/OvRTests/TestResources
        onDemand: false
      - path: TrainCatScreeningMLTests/OvOTests/TestResources
        onDemand: false
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
      - target: MultiLabelClassification
      - target: OvRClassification
      - target: OvOClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.TrainCatScreeningMLTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CSInterface:
    type: framework
    platform: macOS
    sources:
      - path: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CSInterface
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CSConfusionMatrix:
    type: framework
    platform: macOS
    sources:
      - path: CSConfusionMatrix
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CSConfusionMatrix
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  BinaryClassification:
    type: framework
    platform: macOS
    sources:
      - path: BinaryClassification/BinarySources
    resources:
      - path: BinaryClassification/Resources
    dependencies:
      - target: CSInterface
      - target: CSConfusionMatrix
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiClassClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiClassClassification/MultiClassSources
    resources:
      - path: MultiClassClassification/Resources
    dependencies:
      - target: CSInterface
      - target: CSConfusionMatrix
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiLabelClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiLabelClassification/MultiLabelSources
    resources:
      - path: MultiLabelClassification/Resources
    dependencies:
      - target: CSInterface
      - target: CSConfusionMatrix
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiLabelClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvRClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvRClassification/OvRSources
    resources:
      - path: OvRClassification/Resources
    dependencies:
      - target: CSInterface
      - target: CSConfusionMatrix
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvRClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvOClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvOClassification/OvOSources
    resources:
      - path: OvOClassification/Resources
    dependencies:
      - target: CSInterface
      - target: CSConfusionMatrix
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvOClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
