# $ mint run xcodegen

name: ScaryCatScreeningML
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    macOS: "14.0"
targets:
  ScaryCatScreeningML:
    type: tool
    platform: macOS
    sources:
      - path: ScaryCatScreeningML
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ScaryCatScreeningML
        MACOSX_DEPLOYMENT_TARGET: "14.0"

  SCSInterface:
    type: framework
    platform: macOS
    sources:
      - path: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.SCSInterface
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        DEFINES_MODULE: "YES"

  BinaryClassification:
    type: framework
    platform: macOS
    sources:
      - path: BinaryClassification
    resources:
      - path: BinaryClassification/Resources
    dependencies:
      - target: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryClassification
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        DEFINES_MODULE: "YES"

  MultiClassClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiClassClassification
    resources:
      - path: MultiClassClassification/Resources
    dependencies:
      - target: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassClassification
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        DEFINES_MODULE: "YES"
