# $ mint run xcodegen

name: CatScreeningML
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    macOS: "15.2"
targets:
  CatScreeningML:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
      - target: MultiLabelClassification
      - target: OvRClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CatScreeningML
        MACOSX_DEPLOYMENT_TARGET: "15.2"

  CSInterface:
    type: framework
    platform: macOS
    sources:
      - path: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CSInterface
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  BinaryClassification:
    type: framework
    platform: macOS
    sources:
      - path: BinaryClassification/BinaryClassificationSources
    resources:
      - path: BinaryClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  MultiClassClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiClassClassification/MultiClassClassificationSources
    resources:
      - path: MultiClassClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  MultiLabelClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiLabelClassification/MultiLabelClassificationSources
    resources:
      - path: MultiLabelClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiLabelClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  OvRClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvRClassification/OvRClassificationSources
    resources:
      - path: OvRClassification/Resources
    dependencies:
      - target: CSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvRClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
