# $ mint run xcodegen

name: ScaryCatScreeningML
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    macOS: "15.2"
targets:
  ScaryCatScreeningML:
    type: tool
    platform: macOS
    sources:
      - path: ScaryCatScreeningML
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
      - target: MultiLabelClassification
      - target: OvRClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ScaryCatScreeningML
        MACOSX_DEPLOYMENT_TARGET: "15.2"

  SCSInterface:
    type: framework
    platform: macOS
    sources:
      - path: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.SCSInterface
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  BinaryClassification:
    type: framework
    platform: macOS
    sources:
      - path: BinaryClassification/BinaryClassificationSources
    resources:
      - path: BinaryClassification/Resources
    dependencies:
      - target: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  MultiClassClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiClassClassification/MultiClassClassificationSources
    resources:
      - path: MultiClassClassification/Resources
    dependencies:
      - target: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  MultiLabelClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiLabelClassification/MultiLabelClassificationSources
    resources:
      - path: MultiLabelClassification/Resources
    dependencies:
      - target: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiLabelClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"

  OvRClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvRClassification/OvRClassificationSources
    resources:
      - path: OvRClassification/Resources
    dependencies:
      - target: SCSInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvRClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
