# $ mint run xcodegen

name: ScaryCatScreeningML
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    macOS: "14.0"
targets:
  ScaryCatScreeningML:
    type: tool
    platform: macOS
    sources:
      - path: ScaryCatScreeningML
    dependencies:
      - target: BinaryClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ScaryCatScreeningML
        MACOSX_DEPLOYMENT_TARGET: "14.0"

  BinaryClassification:
    type: framework # リソースバンドルも可能なフレームワークとして定義
    platform: macOS
    sources:
      - path: BinaryClassification
    resources:
      - path: BinaryClassification/Resources
        # これにより、BinaryClassification.framework/Resources/ 以下にコピーされます
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryClassification
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        DEFINES_MODULE: "YES" # モジュールを正しく定義するために推奨

  MultiClassClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiClassClassification
    resources:
      - path: MultiClassClassification/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassClassification
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        DEFINES_MODULE: "YES"
