name: Build for Testing

on:
  workflow_call:
    outputs:
      derived_data_artifact_name:
        description: "Name of the DerivedData artifact"
        value: ${{ jobs.build_and_package_derived_data.outputs.derived_data_artifact_name }}
      derived_data_path_on_runner:
        description: "Relative path on the runner where DerivedData was stored"
        value: ${{ jobs.build_and_package_derived_data.outputs.derived_data_path_on_runner }}

jobs:
  build_and_package_derived_data:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
      DERIVED_DATA_PATH: "ci-outputs/test-results/DerivedData"
    outputs:
      derived_data_artifact_name: derived-data-${{ github.run_id }}
      derived_data_path_on_runner: ${{ env.DERIVED_DATA_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Mint packages
        uses: actions/cache@v4
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint
        run: brew install mint

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2' # プロジェクトに応じて調整

      - name: Generate Xcode Project
        run: mint run xcodegen generate

      - name: Create DerivedData Directory
        run: mkdir -p ./${{ env.DERIVED_DATA_PATH }}

      - name: Build for Testing (macOS)
        run: |
          set -o pipefail
          echo "Building CatScreeningML for testing on macOS"
          xcodebuild build-for-testing \
            -project "CatScreeningML.xcodeproj" \
            -scheme "CatScreeningML" \
            -destination "platform=macOS" \
            -derivedDataPath ./${{ env.DERIVED_DATA_PATH }} \
            -configuration Debug \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            | xcbeautify

      - name: Upload Derived Data
        uses: actions/upload-artifact@v4
        with:
          name: derived-data-${{ github.run_id }}
          path: ${{ env.DERIVED_DATA_PATH }}
          retention-days: 1 