name: Format and Lint

on:
  workflow_call:
    outputs:
      result:
        description: "Check Result"
        value: ${{ jobs.format-and-lint.outputs.result }}

jobs:
  format-and-lint:
    runs-on: macos-latest
    env:
      MINT_PATH: ${{ github.workspace }}/.mint
    outputs:
      result: ${{ steps.result.outputs.status }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Mint packages
      uses: actions/cache@v4
      with:
        path: ${{ env.MINT_PATH }}
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
    
    - name: Install Mint
      run: brew install mint

    - name: Run SwiftFormat
      run: mint run swiftformat .

    - name: Run SwiftLint
      run: mint run swiftlint

    - name: Check for uncommitted formatting changes
      id: check_format_changes
      run: |
        if git diff --quiet --exit-code; then
          echo "No formatting changes detected by SwiftFormat."
        else
          echo "Warning: SwiftFormat made changes. Please review and commit them."
        fi
        echo "format_status=true" >> $GITHUB_OUTPUT
        
    - name: Set overall check result
      id: result
      run: |
        if [ "${{ steps.check_format_changes.outputs.format_status }}" = "true" ]; then
          echo "status=success" >> "$GITHUB_OUTPUT"
        else
          echo "status=failure" >> "$GITHUB_OUTPUT"
        fi 