name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macos-latest # macOSの最新環境を使用

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app # 使用するXcodeのバージョンを指定

      - name: Install Mint (for XcodeGen)
        run: |
          if ! command -v mint &> /dev/null
          then
            brew install mint
          fi

      - name: Generate Xcode project
        run: mint run xcodegen # プロジェクトファイルからXcodeプロジェクトを生成

      - name: Build and Test All Schemes
        run: |
          xcodebuild test -project CatScreeningML.xcodeproj -scheme CatScreeningML -destination 'platform=macOS'
          # 必要に応じて、各フレームワークのスキームに対してもテストを実行します。
          # 例: xcodebuild test -project CatScreeningML.xcodeproj -scheme BinaryClassification -destination 'platform=macOS'
          #     xcodebuild test -project CatScreeningML.xcodeproj -scheme MultiClassClassification -destination 'platform=macOS'
          # ... 他の分類器スキームも同様
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer 